name: Build QMK firmware

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
    with:
      qmk_repo: modern-hobbyist/qmk_firmware
      qmk_ref: modhobbyist

  publish:
    name: 'QMK Userspace Publish'
    uses: custom_userspace_publish.yml@main
    if: always() && !cancelled()
    needs: build

  via:
    name: 'Add Via.json Files to Release Artifacts'
    runs-on: linux
    if: always() && !cancelled()
    needs: publish
    steps:
      # Step to parse qmk.json and copy via.json files for build targets
      - name: Parse qmk.json and copy via.json files
        run: |
          mkdir -p artifacts

          # Extract keyboard names from qmk.json
          build_targets=$(jq -r '.keyboards[]' qmk.json)

          # For each keyboard, copy the corresponding via.json if it exists
          for target in $build_targets; do
            if [ -f "$target/via.json" ]; then
              cp "$target/via.json" artifacts/
            fi
          done

      # Upload the via.json files for the specified build targets
      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: via-json-files
          path: artifacts/*.via.json
