name: Build QMK firmware

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
    with:
      qmk_repo: modern-hobbyist/qmk_firmware
      qmk_ref: modhobbyist

  publish:
    name: 'QMK Userspace Publish'
    uses: ./.github/workflows/custom_userspace_publish.yml
    if: always() && !cancelled()
    needs: build
